### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by vitcpp** [postgrespro/pgsphere#28]

**Comment by vitcpp** [comment]
I also found a possible fix for make test. If to replace init_test with init in TESTS = ... everything should be ok. In this issue we should check what is the difference between sql/init.sql and sql/init_test.sql. May be, sql/init.sql is enough?

![image](https://github.com/postgrespro/pgsphere/assets/3510112/4011da65-ce1a-4263-a5ba-364a08812a69)

**Comment by esabol** [comment]
I have a fix for the `USE_HEALPIX=0` case, but I can't compile the code with `USE_HEALPIX=1` to get the expected output in that scenario. If someone could compile PR #26 with HEALPix support and upload the `regression.diffs` file for `make test`, I could include include the fix for `make test` in PR #26, but maybe it should be a separate PR?

Oh, I just realized I could leverage the Travis CI to do this! I'll try doing that.

**Comment by esabol** [comment]
> I also found a possible fix for make test. If to replace init_test with init in TESTS = ... everything should be ok. In this issue we should check what is the difference between sql/init.sql and sql/init_test.sql. May be, sql/init.sql is enough?

Oh, interesting! That would simplify things, certainly. I'll take a look.

**Comment by vitcpp** [comment]
The issue is fixed by @esabol in one PR with issue #26
